site_name: "Alvin Ben George"
site_url: "https://alvinbengeorge.github.io"
nav:
  - Home: index.md

theme:
  name: material
  features:
    - navigation.tabs
  pallete: 
    - scheme: slate

  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
